-- MySQL Script generated by MySQL Workbench
-- Thu Nov  3 09:06:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema deemodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema deemodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `deemodb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `deemodb` ;

-- -----------------------------------------------------
-- Table `deemodb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deemodb`.`clientes` (
  `id_cadastro` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `rua` VARCHAR(255) NOT NULL,
  `bairro` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(255) NOT NULL,
  `cep` VARCHAR(255) NOT NULL,
  `cidade` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_cadastro`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `deemodb`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deemodb`.`fornecedores` (
  `id_fornecedor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR (255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_fornecedor`, `cnpj`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `deemodb`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deemodb`.`produtos` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(255) NOT NULL,
  `tamanho` INT NOT NULL,
  `cor` VARCHAR(255) NOT NULL,
  `marca` VARCHAR(255) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `quantidade` INT NOT NULL,
  `fornecedores_id_fornecedor` INT NOT NULL,
  PRIMARY KEY (`id_produto`, `fornecedores_id_fornecedor`),
  INDEX `fk_produtos_fornecedores1_idx` (`fornecedores_id_fornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_fornecedores1`
    FOREIGN KEY (`fornecedores_id_fornecedor`)
    REFERENCES `deemodb`.`fornecedores` (`id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `deemodb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deemodb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `deemodb`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deemodb`.`venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `preco` DOUBLE NOT NULL,
  `data` VARCHAR(50) NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `clientes_id_cadastro` INT NOT NULL,
  PRIMARY KEY (`id_venda`, `usuario_id_usuario`, `clientes_id_cadastro`),
  INDEX `fk_venda_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_venda_clientes1_idx` (`clientes_id_cadastro` ASC) VISIBLE,
  CONSTRAINT `fk_venda_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `deemodb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_clientes1`
    FOREIGN KEY (`clientes_id_cadastro`)
    REFERENCES `deemodb`.`clientes` (`id_cadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `deemodb`.`venda_has_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deemodb`.`venda_has_produtos` (
  `venda_id_venda` INT NOT NULL,
  `produtos_id_produto` INT NOT NULL,
  PRIMARY KEY (`venda_id_venda`, `produtos_id_produto`),
  INDEX `fk_venda_has_produtos_produtos1_idx` (`produtos_id_produto` ASC) VISIBLE,
  INDEX `fk_venda_has_produtos_venda_idx` (`venda_id_venda` ASC) VISIBLE,
  CONSTRAINT `fk_venda_has_produtos_venda`
    FOREIGN KEY (`venda_id_venda`)
    REFERENCES `deemodb`.`venda` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_has_produtos_produtos1`
    FOREIGN KEY (`produtos_id_produto`)
    REFERENCES `deemodb`.`produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

